name: build and publish to Docker Hub
on:
  schedule:
    - cron:  '5 12 * * *'
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/.github/requirements.txt
      -
        name: execute py script 
        run: |
          python $GITHUB_WORKSPACE/.github/helper.py
      -
        name: Login to DockerHub
        if: env.build_container == 'true'
        uses: docker/login-action@v1.11.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: env.build_container == 'true'
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kreynoldsf5/vesctl:latest, kreynoldsf5/vesctl:${{ env.tag }}
      -
        name: Update repo description
        if: env.build_container == 'true'
        uses: peter-evans/dockerhub-description@v2.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: kreynoldsf5/vesctl
      -
        name: Image digest
        if: env.build_container == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}