name: build container and publish to Docker Hub
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/.github/requirements.txt
      -
        name: execute py script 
        run: |
          python $GITHUB_WORKSPACE/.github/helper.py
      - 
        name: debug
        run: |
          ls -al
      -
        name: Login to DockerHub
        if: env.build_container == 'true'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: env.build_container == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kreynoldsf5/vesctl-test:latest, kreynoldsf5/vesctl-test:${{ env.tag }}
      -
        name: Update repo description
        if: env.build_container == 'true'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: kreynoldsf5/vesctl-test