name: build container and publish to Docker Hub (if needed)
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      -
        name: execute py script 
        run: |
          python helper.py
      -
        name: Login to DockerHub
        if: ${{ env.action_continue }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: ${{ env.action_continue }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kreynoldsf5/vesctl:latest, kreynoldsf5/vesctl:${{ env.tag }}
      -
        name: Update repo description
        if: ${{ env.action_continue }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: kreynoldsf5/vesctl
      -
        name: Image digest
        if: ${{ env.action_continue }}
        run: echo ${{ steps.docker_build.outputs.digest }}